# Generated by Django 5.1.4 on 2025-07-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="user_skills",
            new_name="users_skill",
        ),
    ]
