services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn PROFO.wsgi:application"  # Changed from 'profo' to 'PROFO'
    envVars:
      - key: DJANGO_SECRET_KEY
        value: 1234  # Generate a real one!
      - key: DJANGO_SETTINGS_MODULE
        value: PROFO.settings  # Match case with your project